<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Phalcon Blog</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100 mr-5" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
            <div class="nav-item text-nowrap bg-info text-white btn btn-outline-info pt-2 pb-2  px-5 mr-2">
                <?php
                echo "Hello," . "  " . $this->session->get('activeUser');
                ?>
            </div>
        </div>

        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3{ mr-" href="logout">Sign out</a>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/admin/dashboard">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/blog">
                                <span data-feather="file"></span>
                                Blogs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/addblog">
                                <span data-feather="shopping-cart"></span>
                                Add Blog
                            </a>
                        </li>
                        <a class="nav-link active" aria-current="page" href="/admin/adduser">
                            <span data-feather="home"></span>
                            Add User
                        </a>
                        </li>

                    </ul>
                </div>
            </nav>


            <main class='col'>


                <body>

                    <h2 class="text mt-3 text-dark">Add Blog</h2>

                    <?php echo $this->tag->form(""); ?>
                    <div class="text-active float-center form-group">
                        <p>
                            <label for="full_name">Blog Title</label>
                            <?php echo $this->tag->textField(["title", 'placeholder' => 'Title', 'style' => 'width:100%; padding:10px']); ?>
                        </p>
                        <p>
                            <label for="username">Blog Content</label>
                            <?php echo $this->tag->textArea(["content", 'placeholder' => 'Enter details here...', 'style' => 'width:100%; height: 200px; padding:10px']); ?>
                        </p>
                       <?php if($blogError) { ?>
                        <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
                            <?php echo $blogError; ?>
                        </div>
                        <?php  }?>
                        <p>
                            <?php echo $this->tag->submitButton(["Add Blog", 'name' => 'addBlog', 'class' => 'btn btn-outline-primary mb-2 mt-3', 'style' => "width: 20%"]); ?>
                        </p>
                    </div>

                    </form>

                </body>
            </main>