<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Admin Dashboard</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


  <style>
    table,
    thead,
    tr,
    tbody,
    th,
    td {
      text-align: center;
    }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Phalcon Blog</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100 mr-5" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
      <div class="nav-item text-nowrap bg-info text-white btn btn-outline-info pt-2 pb-2  px-5 mr-2">
        <?php
        echo "Hello," . "  " . $this->session->get('activeUser');
        ?>
      </div>
    </div>

    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3{ mr-" href="logout">Sign out</a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-fixed pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admin/dashboard">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/blog">
                <span data-feather="file"></span>
                Blogs
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/addblog">
                <span data-feather="shopping-cart"></span>
                Add Blog
              </a>
            </li>
            <a class="nav-link active" aria-current="page" href="/admin/adduser">
              <span data-feather="home"></span>
              Add User
            </a>
            </li>

          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap 
      align-items-center pt-3 pb-2 mb-3 border-bottom ">
          <h1 class="h2">Dashboard</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2" float-left>
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        <p class="text text-muted">Users List</p>
        <div class="table-responsive">
          <table class="table table-hover table-sm">
            <thead class="table table-dark">
              <tr class="float-center">
                <th scope="col">User ID</th>
                <th scope="col">Full Name</th>
                <th scope="col">User Name</th>
                <th scope="col">Email</th>
                <th scope="col">Status</th>
                <th scope="col">Change Status</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>
            <?php

            foreach ($users as $row) {
              // $color=$row->status == "pending" ? "danger" : $row->status == "approved" ? "success" : $row->role == "admin" ? "muted" : "dark";?>
            
              <tbody class="table table-striped">
                <tr class='text text-<?php echo $row->status == "pending" ? "danger" : "success" ;?>'>
                  <td><?php echo $row->user_id; ?></td>
                  <td><?php echo $row->full_name; ?></td>
                  <td><?php echo $row->username; ?></td>
                  <td><?php echo $row->email; ?></td>
                  <td><?php echo $row->status; ?></td>
                  <td>
                    <form action="" method="post">
                      <input type="hidden" name="statusName" value="<?php echo $row->status ?>">
                      <input type="hidden" name="id" value="<?php echo $row->user_id ?>">
                      <input type='submit' class='btn btn-warning' name='change' value='Change'>

                    </form>
                  </td>
                  <td>
                    <form action="" method="post">
                      <input type="hidden" name="id" value="<?php echo $row->user_id ?>">
                      <input type='submit' class='btn btn-danger' name='delete' value='Delete' />

                    </form>
                  </td>
                </tr>
              <?php
            }
            // echo $statusName;
            // echo $id;
            echo $msg;
              ?>
              </tbody>
          </table>
        </div>
      </main>
    </div>
  </div>
  <?php
  ?>

  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>